Do not ignore staged PRs
measurement-factory/anubis pull request #66
Opened 2024-02-26 14:58 UTC by eduard-bagdasaryan

2025-03-11 12:33 UTC, eduard-bagdasaryan commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
> Why do we need both run(PrId.Empty()) and run(null)?

As you noted, the difference between these two calls is that the first case gives an array of one PrId element, while the second one gives an empty array (i.e., the RepoMerger._prIds array which will be processed further). In turn, PrMerger._prNumbersFromIds() gives different results for these two cases: an empty updatedPrs array for the first case and null for the second. Thus it distinguishes these two cases, outlined in the code comment:
```
// Treat the 'null' updatedPrs below as if all PRs have been 'updated'.
// An empty updatedPrs means that none of the PRs has been updated.
```
IIRC, basically run(null) means that there is no problem - just a startup case. run(PrId.Empty()) means that there was some problem with the event (or we could not parse it). Having encountered a problem, we indicate it, discard our optimization and process all PRs as usual.

2025-03-11 14:32 UTC, rousskov commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
> > Why do we need both run(PrId.Empty()) and run(null)?
> 
> As you noted, the difference between these two calls is that the first case gives an array of one PrId element, while the second one gives an empty array

Hm... The second call has a null array rather than an empty one, but I assume that a null array parameter gets converted into an empty array somewhere or that this distinction/discrepancy is unimportant in this discussion context.

> In turn, PrMerger._prNumbersFromIds() gives different results for these two cases: an empty updatedPrs array for the first case and null for the second

It is null for the first and an empty array for the second case AFAICT, but that mapping probably does not matter: To answer my question we need to look what happens to those two different _intermediate_ results.

> ```
> // Treat the 'null' updatedPrs below as if all PRs have been 'updated'.
> // An empty updatedPrs means that none of the PRs has been updated.
> ```

The two cases in this Javascript comment do not seem to match the two cases in my question: I do not know which of the two cases in the above Javascript comment corresponds to the first "array of one PrId element" (i.e. `run(PrId.Empty())`) case in my question.
 
> IIRC, basically run(null) means that there is no problem - just a startup case.

"no problem" and "startup case" feel like two different (albeit overlapping) set of cases. Startup case naturally means "process all PRs". If possible, let's use that description/purpose for `run(null)`.

> run(PrId.Empty()) means that there was some problem with the event (or we could not parse it). Having encountered a problem, we indicate it, discard our optimization and process all PRs as usual.

OK, that description matches my expectation. I assert that "process all PRs" is what run(null) also does. We can "indicate" that we have found a problem when we find it. We can "discard" cache when the array is null (there will be nothing to discard at startup, but that is OK). We can process all PRs when the array is null. If that is true, then we do not need PrId.Empty() because we can use null instead. Am I missing something here?

2025-03-11 17:25 UTC, eduard-bagdasaryan commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
> gets converted into an empty array somewhere 

It is converted to RepoMerger._prIds, as I noted above.
This array accumulates all events (as PrId objects), occurred while the current RepoMerger._running is true.

I'd like to clarify this design to avoid confusion. Each event leads to RepoMerger.run(prIds,...) call. In most cases, each event conveys information about one PR, and, hence, produces one PrId object, but, IIRC, some events (workflow_run?) may affect several PRs and therefore produce an array of PrIds objects. If an event is correctly parsed/processed, a 'non-empty' PrId is created (by means of its static methods except Empty()). If an event could not be parsed/processed, an 'empty' PrId is created with PrId.Empty(). All these PrId objects are then stored in RepoMerger._prIds. When RepoMerger.run() starts next iteration, RepoMerger._prIds (which may contain by that time some empty and some non-empty PrId objects) is passed to PrMerger.execute() which analyses whether the optimization should be applied. It treats an empty PrId object as an indication that the optimization is not applicable. RepoMerger.run(null) does not add any PrId object into RepoMerger._prIds (which is an empty array at startup and thus remains empty after the initial RepoMerger.run(null).

We could use another design, calling RepoMerger.run(null) instead of RepoMerger.(PrId.Empty()) from event handlers and modifying RepoMerger.run() so that it would clear RepoMerger._prIds in this case. It would have no effect at startup (RepoMerger._prIds is empty anyway) and it would clear the cache (a non-empty RepoMerger._prIds) upon an event-handling error. Unfortunately I could not exactly recollect why the first design was chosen then (and whether we had discussed it). Probably I considered that we should not clear RepoMerger._prIds cache any time an event could not be parsed, but postpone the decision to a higher-level code (i.e., PrMerger), that produces the final PR number list and could give some useful debugging (e.g., the list of PR numbers that could have been processed unless an error).

2025-03-11 19:35 UTC, rousskov commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
I think we are more-or-less on the same page regarding the current design (up to and including this PR code). I continue to suspect that the current design should be replaced with a much simpler one, completely eliminating "empty PrId" and associated (seemingly unnecessary) complications.

In my analysis, I start with what PR processing code needs (rather than focusing on details of providing that code with what it needs). In this context, PR processing code needs exactly one thing: A list of PRs to process. It does not need PrIds, and it especially does not need "empty" PrIds. Current PrIds code is just a tool that translates input (i.e. raw GitHub events) into output (i.e. a list of PRs to process). That translation can be done using several different algorithms/tools, of course.

It is understood that the list of PRs to (eventually) process may grow with time as Anubis receives more and more events while it is unable to start processing (for reasons irrelevant to this discussion) or while it is processing the previously collected list. It is also understood that the list of PRs to process is bounded by "all PRs" -- it cannot grow beyond that "everything is included" set. In other words, a list of PRs grows until it it reaches an "all PRs" state.

I then move lower one "level" and recognize that there are two kinds of events: Events that lead to one or more event-specific PRs added to the list of PRs process and events that lead to "process all PRs" outcome.

I suggest that we represent a "list of PRs to process" using an Array pointer (called "PrsToProcess" in the text below):

* When PrsToProcess is nil, all PRs must be processed from scratch. Previously cached PR information must be discarded at the beginning of that "from scratch" processing.
* Otherwise, PrsToProcess represents PRs that must be processed, using cached PR information as needed.

Here is how PrsToProcess changes throughout Anubis lifecycle:

* PrsToProcess starts as a nil pointer.
* A non-nil PrsToProcess can grow as event handlers add more PRs to the array. A nil PrsToProcess cannot grow; adding PRs to a nil array does nothing -- the pointer remains nil.
* After PrsToProcess has been processed, it is reset to point to an empty array.

When Anubis encounters an applicable error, it sets PrsToProcess to a nil pointer, triggering future processing of "all PRs (without caching)".

The above is a rough high-level sketch. Does it have any design-level flaws? Is it enough to refactor this PR?

N.B. Please address the [other change request](https://github.com/measurement-factory/anubis/pull/66#discussion_r1987378610) first. That (simple) change request does not depend on this discussion and on the corresponding complex code refactoring AFAICT.

2025-03-11 21:45 UTC, eduard-bagdasaryan commented on src/PrMerger.js
> +                if (!clearedForMerge && !updated && lastScan && lastScan.isStillUnchanged(rawPr, currentScan.scanDate)) {
Posted [PR70](https://github.com/measurement-factory/anubis/pull/70/files).

2025-03-11 23:39 UTC, eduard-bagdasaryan commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
Ok, let's refactor it.

2025-03-12 18:27 UTC, eduard-bagdasaryan commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
> A non-nil PrsToProcess can grow as event handlers add more PRs to the array.

The point is that event handlers yield events metadata and fill, say, EventsToProcess array, rather than ready-for-use PR numbers because there is an extra step to deduce PR number from the data gathered from events (PrId object). This extra step may be costly, involving additional GitHub API calls, so we probably do not want make it immediately for each event but accumulate until the next PR processing iteration begins (avoiding event->PrNum conversions overhead for scenarios when the cache is going to be cleared).
So I'll try to follow your sketch with the difference that we keep caching events (i.e., PrId objects) and convert it to PrsToProcess at the start of each PR processing iteration.

2025-03-12 18:46 UTC, rousskov commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
> we keep caching events (i.e., PrId objects) and convert it to PrsToProcess at the start of each PR processing iteration.

I would like to make two clarifications:

* My refactoring request is _not_ about PrId class removal. It is about removal of special "empty" PrId objects. To address my request, it is perfectly fine to keep storing PrId objects in "cached events" array (the exact array name is irrelevant to this change request and EventsToProcess name may be better than PrsToProcess!).
* The "PrsToProcess changes throughout Anubis lifecycle" apply to that cached events array. They all happen _before_ that expensive conversion from the cached events list to the list of PRs. At that conversion time, the cached events array becomes empty.

However, on a separate note, we should justify PrId class addition/existence! I do understand that conversion from events to PR numbers is costly and should be delayed -- thank you for detailing that for me. That delay implies we have to store information. What I do not yet understand is why we want to store "preprocessed events" (i.e. PrId objects) instead of storing events themselves (postponing any non-trivial processing until that expensive conversion time).

2025-03-12 20:20 UTC, eduard-bagdasaryan commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
>  why we want to store "preprocessed events"

We usually need only one specific field of an event object (that may contain dozens of fields) so storing entire event objects looks as a needless overhead, especially when an event allows to extract the PR number immediately (e.g., "pull_request" event). Also some different events yield the same information (e.g, PR number can be also extracted from the "pull_request_review" event). Basically, we have only few useful event data - PR number, PR branch and SHA and it looks reasonable to extract it immediately from a much greater number of events.
In the alternative approach we store all events in an array and then have a method with many "else if" for each event type, basically duplicating the already existing code in Main.js (where each "else if" corresponds to an WebhookHandler.on() hook).

2025-03-13 14:13 UTC, eduard-bagdasaryan commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
Done (36a6cdc).

2025-03-13 18:16 UTC, rousskov commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
> In the alternative approach we store all events in an array and then have a method with many "else if" for each event type, basically duplicating the already existing code in Main.js (where each "else if" corresponds to an WebhookHandler.on() hook).

I agree with this part.

2025-03-18 23:26 UTC, eduard-bagdasaryan commented on src/Main.js
> +        Merger.run(Util.PrId.Empty());
I posted the changes, already discussed (e.g., wrappers for event handlers in Main.js) and performed testing with my experimental project. It revealed several problems, fixed in subsequent commits 08dc525 - 6672562.

2025-03-28 22:08 UTC, rousskov requested changes
Excellent progress, thank you! This is a partial review.

2025-03-28 22:08 UTC, rousskov commented on src/PrMerger.js
> +        this.delayedPrs = []; // PRs that were delayed during the scan (an array of {prNumber, expirationDate} pairs)
```suggestion

        // PRs that wait for some timeout to expire.
        // Each array element is an {number, expirationDate} structure,
        // where the number field represents PR number (of XXX type) and
        // expirationDate member has a Date type
        this.delayedPrs = [];

```

2025-03-31 12:49 UTC, eduard-bagdasaryan reviewed
Done (up to ceaf9d6).

2025-03-31 12:49 UTC, eduard-bagdasaryan commented on src/PrMerger.js
> +        this.delayedPrs = []; // PRs that were delayed during the scan (an array of {prNumber, expirationDate} pairs)
Done.

2025-03-31 12:49 UTC, eduard-bagdasaryan commented on src/Main.js
> +    if (e.head_branch === Config.stagingBranch()) {
Done.

2025-03-31 12:49 UTC, eduard-bagdasaryan commented on src/Main.js
> +    HandlerWrap(anEv, (ev) => {
Done.

2025-03-31 12:49 UTC, eduard-bagdasaryan commented on src/Main.js
> +        Merger.run(Util.PrId.PrNum(pr.number));
Done (in case I saw through your suggestion correctly).

2025-03-31 14:58 UTC, rousskov requested changes

2025-03-31 14:58 UTC, rousskov commented on src/Main.js
> +            assert(prIds);
```suggestion
            assert(prIds);
            Logger.info("PrIds discovered by the event handler:", prIds.length);
```

2025-03-31 14:58 UTC, rousskov commented on src/Main.js
> +            // e.pull_requests is empty, e.g., for master commits
```suggestion
            // workflow runs for other non-PR branches (e.g., master) are not associated with PRs
```

2025-03-31 14:58 UTC, rousskov commented on src/Main.js
> +            // e.check_suite.pull_requests is empty, e.g., for master commits
Please apply two workflow_run changes here as well (`s/workflow/check/`).

2025-03-31 14:58 UTC, rousskov commented on src/PrMerger.js
> +                return false; // this scan has not seen freshRawPR (neither awakePrs no delayedPrs have it)
```suggestion
                return false; // this scan has not seen freshRawPr (neither awakePrs nor delayedPrs have it)
```

2025-03-31 14:58 UTC, rousskov commented on src/PrMerger.js
> +                if (currentPr && (id.value === this._stagedBranchSha)) {
```suggestion
                assert(!currentPr || this._stagedBranchSha !== null);
                if (currentPr && (id.value === this._stagedBranchSha)) {
```

2025-03-31 14:58 UTC, rousskov commented on src/RepoMerger.js
> +    // prIds (if provided) an array of Util.PrId elements filled by an event
```suggestion
    // prIds is an array of Util.PrId objects collected by event handlers (or null)
```

2025-03-31 14:58 UTC, rousskov commented on src/RepoMerger.js
> +        // else keep discarding prIds until next rerun (prIds !== null && this._prIds === null)
```suggestion
        // else keep discarding prIds until this._prIds is reset below
```

2025-03-31 14:58 UTC, rousskov commented on src/RepoMerger.js
> +                const ids = this._prIds;
```suggestion
                const ids = this._prIds; // may be null
```

2025-03-31 14:58 UTC, rousskov commented on src/Main.js
> +        return Util.PrId.PrNumList(list);
I suspect the code becomes simpler or more readable if this snippet is moved to the top of the handler, protected by the `e.pull_requests.length` condition: If GitHub tells us associated PRs, use that info. Otherwise, handle the special case of a staged branch. Please try that processing order.

2025-04-01 14:55 UTC, eduard-bagdasaryan reviewed
Done (up to 62c38df).

2025-04-01 15:33 UTC, rousskov commented on src/PrMerger.js
>          const savedRawPr = this.awakePrs.find(el => el.number === freshRawPr.number);
```suggestion
        // XXX: The above concern also applies to PRs that are not "cleared for
        // merging" but can be proactively staged in anticipation of that
        // clearance. TODO: Mark the first such PR that is waiting for the
        // staging branch "lock" and treat it as "changed", returning false.

        const savedRawPr = this.awakePrs.find(el => el.number === freshRawPr.number);
```

2025-04-02 21:10 UTC, rousskov requested changes
I only have a few polishing requests. I hope they can be done safely, without a lot of retesting.

2025-04-02 21:10 UTC, rousskov commented on src/Util.js
> +// Represents a PR 'identificator' as a string, either of
```suggestion
// Identifies or refers to a PR using either
```

2025-04-02 21:10 UTC, rousskov commented on src/Util.js
> +    static PrNumList(list) { return Array.from(list, prNum => new PrId("prNum", prNum.toString())); }
Why do we need to convert PR numbers to strings? If it is not going to cause problems, let's store them as integers/numbers. There are other similarly strange expressions like `id.value.toString()` elsewhere that will probably go away if we do not have to convert.

2025-04-03 14:49 UTC, eduard-bagdasaryan reviewed
Done.

2025-04-03 15:19 UTC, rousskov approved these changes

2025-04-04 14:03 UTC, merged